title: Suvo Ghosh Hazra  # your name (or website title) here
logo: "/images/dp.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br><br>
  <b>TECH I. S.<b>
  <br>
  Data Scientist 
  <br>
  Python Connoisseur
  <br><br>
  <a href="https://www.linkedin.com/in/suvo-ghosh-hazra/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
